version: '3.1'

services:
    mysql:
        image: mysql:5.7
        container_name: mysql_container_WhatsNext
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Use a secure password
            MYSQL_DATABASE: ${DB_DATABASE:-whatsnext_db} # Database to be created automatically
            MYSQL_USER: ${DB_USERNAME} # Admin username
            MYSQL_PASSWORD: ${DB_PASSWORD} # Admin password
        volumes:
            - mysql_data:/var/lib/mysql
            - ./init:/docker-entrypoint-initdb.d # Initialization scripts
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_WhatsNext
        environment:
            PMA_HOST: mysql # Use the service name of MySQL as the host
            PMA_PORT: 3306
            PMA_USER: ${DB_USERNAME} # Optional: For auto-login in phpMyAdmin
            PMA_PASSWORD: ${DB_PASSWORD} # Optional: For auto-login in phpMyAdmin
        ports:
            - "8080:80"
        depends_on:
            - mysql

    # Laravel Application Service
    app:
        image: mrnaga619/whatsnext:latest
        container_name: laravel_app_WhatsNext
        ports:
            - "80:80"
        depends_on:
            - mysql

volumes:
    mysql_data:
